#!/usr/bin/env node
// Deliberately dependency-light: use the project's TypeScript, then the
// distro/runtime TypeScript. No project code is executed.
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const cwd = process.cwd(), args = process.argv.slice(2);
const value = n => { const i=args.indexOf(n); return i >= 0 ? args[i+1] : undefined; };
if (args.includes("--help")) { console.log(`Code Doctor\n\nUsage: code-doctor [--full] [--changed] [--project path] [--json] [--quiet] [--fail-on never|error|warning|deprecated]`); process.exit(0); }
if (args.includes("--version")) { console.log("code-doctor 1.0.0"); process.exit(0); }
let ts; let tsSource="fallback";
for (const base of [cwd, path.dirname(cwd), path.dirname(process.execPath), "/usr/lib/node_modules", "/usr/local/lib/node_modules"]) try { ts=require(require.resolve("typescript", { paths:[base] })); tsSource=base; break; } catch {}
if (!ts) { console.error("Code Doctor: TypeScript is unavailable. Install it in the project (npm/pnpm/yarn add -D typescript)."); process.exit(2); }
const ignored = new Set(["node_modules",".git","dist","build","coverage",".next",".nuxt",".svelte-kit",".turbo","out",".cache",".code-doctor"]);
function walk(dir, out=[]) { for (const e of fs.readdirSync(dir,{withFileTypes:true})) { if(ignored.has(e.name)) continue; const f=path.join(dir,e.name); if(e.isDirectory()) walk(f,out); else out.push(f); } return out; }
const rel=f=>path.relative(cwd,f)||".";
const sourceExt=/\.(?:ts|tsx|js|jsx|mts|cts|mjs|cjs)$/;
function configs(){ const p=value("--project"); if(p) return [path.resolve(cwd,p)]; return walk(cwd).filter(f=>path.basename(f)==="tsconfig.json").sort(); }
function programFor(config){ const c=ts.readConfigFile(config,ts.sys.readFile); if(c.error) throw Error(ts.flattenDiagnosticMessageText(c.error.messageText,"\n")); const p=ts.parseJsonConfigFileContent(c.config,ts.sys,path.dirname(config),undefined,config); return ts.createProgram({rootNames:p.fileNames,options:p.options,projectReferences:p.projectReferences}); }
function jsProgram(){ return ts.createProgram({rootNames:walk(cwd).filter(f=>sourceExt.test(f)),options:{allowJs:true,checkJs:true,noEmit:true,target:ts.ScriptTarget.ESNext,module:ts.ModuleKind.ESNext,moduleResolution:ts.ModuleResolutionKind.Bundler,skipLibCheck:true}}); }
const flatten=x=>Array.isArray(x)?x.map(y=>y.text??"").join(""):String(x??"");
const depr=s=>{ const t=s?.getJsDocTags?.()?.find(x=>x.name==="deprecated"); return t ? (flatten(t.text).trim()||"This API is marked @deprecated.") : null; };
function packageName(f){ const p=f.replaceAll(path.sep,"/").split("/node_modules/").pop(); if(!f.includes("/node_modules/")) return null; const a=p.split("/"); return a[0]?.startsWith("@")?a.slice(0,2).join("/"):a[0]; }
function loc(sf,pos){const x=sf.getLineAndCharacterOfPosition(pos);return {line:x.line+1,column:x.character+1};}
function scan(program, project){ const checker=program.getTypeChecker(), findings=[], seen=new Set(); const add=(sf,node,symbol,message,decl)=>{const l=loc(sf,node.getStart(sf)); const k=`${rel(sf.fileName)}:${l.line}:${l.column}:${symbol}`; if(seen.has(k)) return; seen.add(k); findings.push({ruleId:"deprecated-api",severity:"warning",file:rel(sf.fileName),line:l.line,column:l.column,symbol,message,declaration:decl?rel(decl):null,package:decl?packageName(decl):null,snippet:node.getText(sf).slice(0,180),project});};
 for(const sf of program.getSourceFiles()){if(sf.isDeclarationFile||sf.fileName.includes("/node_modules/"))continue; const visit=n=>{if(ts.isIdentifier(n)||ts.isPrivateIdentifier(n)){let s=checker.getSymbolAtLocation(n), orig=s; if(s?.flags&ts.SymbolFlags.Alias) try{s=checker.getAliasedSymbol(s)}catch{}; const m=depr(s)||depr(orig); if(m){const d=s?.declarations?.[0]||orig?.declarations?.[0]; add(sf,n,s?.getName?.()||n.text,m,d?.getSourceFile().fileName)}}; ts.forEachChild(n,visit)}; visit(sf); }
 return findings; }
function compiler(program,project){return ts.getPreEmitDiagnostics(program).map(d=>{const p=d.file&&typeof d.start==="number"?loc(d.file,d.start):{line:null,column:null};return {ruleId:"typescript-error",severity:d.category===ts.DiagnosticCategory.Error?"error":"warning",code:`TS${d.code}`,file:d.file?rel(d.file.fileName):null,line:p.line,column:p.column,message:ts.flattenDiagnosticMessageText(d.messageText,"\n"),project};});}
function textScan(){const out=[]; for(const f of walk(cwd).filter(x=>sourceExt.test(x))){const lines=fs.readFileSync(f,"utf8").split(/\r?\n/); lines.forEach((line,i)=>{const checks=[[/@ts-ignore\b/,"ts-ignore","warning"],[/@ts-nocheck\b/,"ts-nocheck","error"],[/eslint-disable-next-line\b|eslint-disable\b/,"eslint-disable","warning"],[/@ts-expect-error\b(?![^\n]*--|[^\n]*\S+\s+\S)/,"undocumented-ts-expect-error","warning"],[/\bas\s+any\b|:\s*any\b|<any>/,"explicit-any","warning"],[/\b[A-Za-z_$][\w$]*!\./,"non-null-assertion","warning"]]; checks.forEach(([re,r,s])=>{if(re.test(line))out.push({ruleId:r,severity:s,file:rel(f),line:i+1,column:line.search(re)+1,message:r==="undocumented-ts-expect-error"?"Add a reason after -- (for example: upstream issue #123).":"Review this escape or suppression.",snippet:line.trim().slice(0,180)});});});} return out;}
function changed(){const r=spawnSync("git",["diff","--name-only","HEAD","--","*.ts","*.tsx","*.js","*.jsx","*.mts","*.cts","*.mjs","*.cjs"],{cwd,encoding:"utf8"});return new Set((r.stdout||"").split(/\r?\n/).filter(Boolean));}
function optional(tool){const r=spawnSync(tool,["--version"],{cwd,encoding:"utf8",stdio:"ignore"});return r.status===0;}
const projects=[], findings=[], diagnostics=[]; for(const c of configs().length?configs():[null]) try{const p=c?programFor(c):jsProgram();projects.push(c?rel(c):"<auto-js>"); findings.push(...scan(p,c?rel(c):"<auto-js>")); diagnostics.push(...compiler(p,c?rel(c):"<auto-js>"));}catch(e){diagnostics.push({ruleId:"doctor-config",severity:"error",message:String(e),file:c?rel(c):null,line:null,column:null});}
let all=[...findings,...diagnostics,...textScan()]; const ch=args.includes("--changed")?changed():null; if(ch) all=all.filter(x=>!x.file||ch.has(x.file)); all=[...new Map(all.map(x=>[`${x.ruleId}|${x.file}|${x.line}|${x.column}|${x.symbol||x.code||x.message}`,x])).values()];
const report={schemaVersion:1,generatedAt:new Date().toISOString(),repository:path.basename(cwd),cwd,typescriptVersion:ts.version,typescriptSource:tsSource,projects,summary:{errors:all.filter(x=>x.severity==="error").length,warnings:all.filter(x=>x.severity==="warning").length,deprecated:all.filter(x=>x.ruleId==="deprecated-api").length},findings:all};
const out=path.resolve(cwd,value("--out")||".code-doctor"); fs.mkdirSync(out,{recursive:true}); fs.writeFileSync(path.join(out,"report.json"),JSON.stringify(report,null,2)+"\n");
const priority={error:0,warning:1}; const md=["# Code Doctor Remediation","","Fix the findings below.","","- Read surrounding code before modifying it.","- Prefer supported APIs over suppressions or `any`.","- Preserve behavior and run existing tests.","- Rerun `code-doctor --full` after fixes.","",`Summary: ${report.summary.errors} errors, ${report.summary.warnings} warnings, ${report.summary.deprecated} deprecated APIs.` ,""]; for(const f of [...all].sort((a,b)=>(priority[a.severity]??2)-(priority[b.severity]??2)||String(a.file).localeCompare(String(b.file)))) { const at=f.file?f.file+(f.line?`:${f.line}:${f.column}`:""):"<project>"; md.push(`- **${f.severity.toUpperCase()} ${f.ruleId}** ${at} — ${f.symbol?`${f.symbol}: `:""}${f.message||""}`); } fs.writeFileSync(path.join(out,"AGENT_FIXES.md"),md.join("\n")+"\n");
const full=args.includes("--full"), tools=full?["eslint","knip"].map(x=>`${x}: ${optional(x)?"available":"not installed"}`):[]; const json=args.includes("--json"); if(json) console.log(JSON.stringify(report)); else if(!args.includes("--quiet")){console.log(`Code Doctor\n────────────\nProject            ${report.repository}\nTypeScript         ${ts.version}\nProjects           ${projects.length}\nErrors             ${report.summary.errors}\nWarnings           ${report.summary.warnings}\nDeprecated APIs    ${report.summary.deprecated}`); if(tools.length) console.log(`Checks             ${tools.join(", ")}`); console.log(`\nReports\n${rel(path.join(out,"report.json"))}\n${rel(path.join(out,"AGENT_FIXES.md"))}`); for(const f of all.slice(0,20)) console.log(`\n${f.severity.toUpperCase()} ${f.ruleId}\n${f.file||"<project>"}:${f.line||""}:${f.column||""}\n${f.message||""}`);}
const fail=value("--fail-on")||"never"; let exitCode=0; if(fail==="deprecated"&&report.summary.deprecated>0) exitCode=1; else if(fail==="error"&&report.summary.errors>0) exitCode=1; else if(fail==="warning"&&(report.summary.errors+report.summary.warnings)>0) exitCode=1; process.exitCode=exitCode;
