#!/usr/bin/env sh
set -eu

[ -n "${THEME_BG:-}" ] || exit 0
[ -n "${THEME_TEXT:-}" ] || exit 0
[ -n "${THEME_ACCENT:-}" ] || exit 0
[ -n "${THEME_ACCENT2:-}" ] || exit 0

cache_dir="${THEME_CACHE_DIR:-$HOME/.cache/hypr}"
shell_theme="$cache_dir/theme-shell.zsh"

bat_themes_dir="$HOME/.config/bat/themes"
bat_theme_file="$bat_themes_dir/NoxflowDynamic.tmTheme"

lazygit_dir="$HOME/.config/lazygit"
lazygit_theme_file="$lazygit_dir/theme.generated.yml"

mkdir -p "$cache_dir" "$bat_themes_dir" "$lazygit_dir"

cat > "$bat_theme_file" <<EOF2
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>NoxflowDynamic</string>
  <key>settings</key>
  <array>
    <dict>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>${THEME_BG}</string>
        <key>foreground</key>
        <string>${THEME_TEXT}</string>
        <key>caret</key>
        <string>${THEME_ACCENT}</string>
        <key>selection</key>
        <string>${THEME_BG_SOFT:-$THEME_BG}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Comment</string>
      <key>scope</key>
      <string>comment</string>
      <key>settings</key>
      <dict><key>foreground</key><string>${THEME_MUTED:-$THEME_TEXT}</string></dict>
    </dict>
    <dict>
      <key>name</key>
      <string>String</string>
      <key>scope</key>
      <string>string</string>
      <key>settings</key>
      <dict><key>foreground</key><string>${THEME_ACCENT2}</string></dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Keyword</string>
      <key>scope</key>
      <string>keyword</string>
      <key>settings</key>
      <dict><key>foreground</key><string>${THEME_ACCENT}</string></dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Constant</string>
      <key>scope</key>
      <string>constant</string>
      <key>settings</key>
      <dict><key>foreground</key><string>${THEME_WARN:-$THEME_ACCENT}</string></dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Invalid</string>
      <key>scope</key>
      <string>invalid</string>
      <key>settings</key>
      <dict><key>foreground</key><string>${THEME_DANGER:-$THEME_ACCENT}</string></dict>
    </dict>
  </array>
</dict>
</plist>
EOF2

if command -v bat >/dev/null 2>&1; then
  bat cache --build >/dev/null 2>&1 || true
fi

cat > "$lazygit_theme_file" <<EOF2
gui:
  theme:
    activeBorderColor: ["${THEME_ACCENT}", "bold"]
    inactiveBorderColor: ["${THEME_MUTED:-$THEME_TEXT}"]
    optionsTextColor: ["${THEME_ACCENT2}"]
    selectedLineBgColor: ["${THEME_BG_SOFT:-$THEME_BG}"]
    selectedRangeBgColor: ["${THEME_BG_SOFT:-$THEME_BG}"]
    cherryPickedCommitBgColor: ["${THEME_BG_SOFT:-$THEME_BG}"]
    cherryPickedCommitFgColor: ["${THEME_ACCENT2}"]
    unstagedChangesColor: ["${THEME_WARN:-$THEME_ACCENT}"]
    defaultFgColor: ["${THEME_TEXT}"]
    searchingActiveBorderColor: ["${THEME_ACCENT2}", "bold"]
EOF2

cat > "$shell_theme" <<EOF2
# Generated by wallpaper theme-sync hook. Do not edit manually.

export FZF_DEFAULT_OPTS="--height=55% --layout=reverse --border=rounded --info=inline-right --pointer='>' --marker='*' --color=fg:${THEME_TEXT},bg:${THEME_BG},hl:${THEME_ACCENT2},fg+:${THEME_TEXT},bg+:${THEME_BG_SOFT:-$THEME_BG},hl+:${THEME_ACCENT},prompt:${THEME_ACCENT2},pointer:${THEME_ACCENT},marker:${THEME_WARN:-$THEME_ACCENT},info:${THEME_MUTED:-$THEME_TEXT}"
export BAT_THEME="NoxflowDynamic"

if [ -f "$HOME/.config/lazygit/config.yml" ]; then
  export LG_CONFIG_FILE="$HOME/.config/lazygit/config.yml,$HOME/.config/lazygit/theme.generated.yml"
else
  export LG_CONFIG_FILE="$HOME/.config/lazygit/theme.generated.yml"
fi
EOF2
