return {
  {
    "folke/snacks.nvim",
    priority = 1000,
    lazy = false,
    ---@type snacks.Config
    opts = {
      bigfile = { enabled = true, notify = false },
      dashboard = { enabled = true },
      explorer = { enabled = true, replace_netrw = true, trash = true },
      indent = { enabled = true, animate = { enabled = false } },
      input = { enabled = true },
      notifier = { enabled = true, timeout = 3000 },
      picker = { enabled = true },
      quickfile = { enabled = true },
      scratch = { enabled = true },
      scope = { enabled = true },
      terminal = { enabled = true },
      animate = { enabled = false },
      scroll = { enabled = false },
      statuscolumn = { enabled = false },
      words = { enabled = false },
      styles = {
        notification = { wo = { winblend = 5 } },
        terminal = { wo = { winhighlight = "Normal:NormalFloat,FloatBorder:FloatBorder" } },
      },
    },
    keys = {
      { "<leader>e", function() Snacks.explorer() end, desc = "File explorer" },
      { "<leader><space>", function() Snacks.picker.smart() end, desc = "Smart files" },
      { "<leader>ff", function() Snacks.picker.files({ cwd = require("noxflow.utils").buf_root(0) }) end, desc = "Find files" },
      { "<leader>fg", function() Snacks.picker.grep({ cwd = require("noxflow.utils").buf_root(0) }) end, desc = "Live grep" },
      { "<leader>fb", function() Snacks.picker.buffers() end, desc = "Find buffers" },
      { "<leader>fr", function() Snacks.picker.recent() end, desc = "Recent files" },
      { "<leader>fp", function() Snacks.picker.projects() end, desc = "Projects" },
      { "<leader>fh", function() Snacks.picker.help() end, desc = "Help tags" },
      { "<leader>fc", function() Snacks.picker.files({ cwd = vim.fn.stdpath("config") }) end, desc = "Config files" },
      { "<leader>ss", function() Snacks.picker.lsp_symbols() end, desc = "Document symbols" },
      { "<leader>sS", function() Snacks.picker.lsp_workspace_symbols() end, desc = "Workspace symbols" },
      { "<leader>sw", function() Snacks.picker.grep_word({ cwd = require("noxflow.utils").buf_root(0) }) end, desc = "Search word" },
      { "<leader>gg", function() Snacks.lazygit() end, desc = "LazyGit" },
      { "<leader>tt", function() Snacks.terminal.toggle(nil, { cwd = require("noxflow.utils").buf_root(0), id = "shell:" .. require("noxflow.utils").buf_root(0) }) end, desc = "Project terminal" },
      { "<leader>tf", function() Snacks.terminal.toggle(nil, { cwd = require("noxflow.utils").buf_root(0), id = "shell-float:" .. require("noxflow.utils").buf_root(0), win = { style = "float" } }) end, desc = "Floating terminal" },
      { "<leader>bd", function() Snacks.bufdelete() end, desc = "Delete buffer" },
      { "<leader>bo", function() Snacks.bufdelete.other() end, desc = "Delete other buffers" },
      { "gd", function() Snacks.picker.lsp_definitions() end, desc = "Go to definition" },
      { "<leader>wv", "<cmd>vsplit<cr>", desc = "Vertical split" },
      { "<leader>ws", "<cmd>split<cr>", desc = "Horizontal split" },
      { "<leader>wq", "<cmd>close<cr>", desc = "Close window" },
    },
  },
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
      delay = 300,
      spec = {
        { "<leader>f", group = "find" },
        { "<leader>s", group = "search" },
        { "<leader>g", group = "git" },
        { "<leader>c", group = "code" },
        { "<leader>x", group = "diagnostics" },
        { "<leader>a", group = "agents" },
        { "<leader>t", group = "terminal" },
        { "<leader>b", group = "buffers" },
        { "<leader>w", group = "windows" },
      },
    },
  },
  {
    "christoomey/vim-tmux-navigator",
    cmd = {
      "TmuxNavigateLeft",
      "TmuxNavigateDown",
      "TmuxNavigateUp",
      "TmuxNavigateRight",
      "TmuxNavigatePrevious",
    },
    keys = {
      { "<C-h>", "<cmd><C-U>TmuxNavigateLeft<cr>", desc = "Navigate left" },
      { "<C-j>", "<cmd><C-U>TmuxNavigateDown<cr>", desc = "Navigate down" },
      { "<C-k>", "<cmd><C-U>TmuxNavigateUp<cr>", desc = "Navigate up" },
      { "<C-l>", "<cmd><C-U>TmuxNavigateRight<cr>", desc = "Navigate right" },
    },
  },
  {
    "tpope/vim-sleuth",
    event = "BufReadPre",
  },
  {
    "windwp/nvim-autopairs",
    event = "InsertEnter",
    opts = {},
  },
}
