local ctx = assert(NOX_HYPR, "NOX_HYPR context missing")
local bind = ctx.bind
local exec = ctx.exec
local home = ctx.home
local mainMod = ctx.mainMod

-- Launch / session
exec(mainMod .. " + Return", ctx.terminal)
exec(mainMod .. " + E", ctx.fileManager)
exec(mainMod .. " + Space", ctx.menu)
exec(mainMod .. " + SHIFT + Space", home .. "/.config/hypr/scripts/launcher.sh --fast")
exec(mainMod .. " + CTRL + Space", ctx.overview)
exec(mainMod .. " + F1", home .. "/.config/hypr/scripts/hypr-binds.sh")
exec(mainMod .. " + Slash", ctx.menu)
exec(mainMod .. " + CTRL + Slash", home .. "/.config/hypr/scripts/hypr-binds.sh")
exec(mainMod .. " + A", ctx.menu)
exec(mainMod .. " + Y", ctx.overview)
exec(mainMod .. " + SHIFT + Y", home .. "/.config/hypr/scripts/panel-switch.sh toggle-view")
exec(mainMod .. " + CTRL + Y", home .. "/.config/hypr/scripts/panel-switch.sh wayle")
exec(mainMod .. " + CTRL + ALT + Y", home .. "/.config/hypr/scripts/panel-switch.sh toggle")
exec(mainMod .. " + CTRL + SHIFT + Y", home .. "/.config/hypr/scripts/theme-pass.sh")
exec(mainMod .. " + D", ctx.menu)
exec(mainMod .. " + comma", home .. "/.config/hypr/scripts/settings-hub.sh")
exec(mainMod .. " + SHIFT + comma", home .. "/.config/hypr/scripts/minimize-window.sh restore")
exec(mainMod .. " + CTRL + comma", home .. "/.config/hypr/scripts/settings-hub.sh quick")
exec(mainMod .. " + ALT + comma", home .. "/.config/hypr/scripts/settings/editor.sh")
exec(mainMod .. " + CTRL + ALT + comma", home .. "/.config/hypr/scripts/app-routing-apply-focused.sh")
exec(mainMod .. " + B", ctx.browser .. " --ozone-platform-hint=auto")
exec(mainMod .. " + G", home .. "/.config/hypr/scripts/layout-switcher.sh cycle")
exec(mainMod .. " + ALT + G", home .. "/.config/hypr/scripts/layout-switcher.sh toggle")
exec(mainMod .. " + P", home .. "/.config/hypr/scripts/monitor-control.sh menu")
exec(mainMod .. " + H", home .. "/.local/bin/hypr-phone menu")
exec(mainMod .. " + SHIFT + H", home .. "/.local/bin/hypr-phone mirror --profile default")
exec(mainMod .. " + CTRL + H", home .. "/.config/hypr/scripts/syncthing-control.sh open-ui")
bind(mainMod .. " + ALT + H", hl.dsp.workspace.toggle_special("phone"))
exec(mainMod .. " + Escape", home .. "/.config/hypr/scripts/power-menu.sh")
exec(mainMod .. " + CTRL + L", home .. "/.config/hypr/scripts/lock.sh")
exec(mainMod .. " + CTRL + ALT + L", home .. "/.config/hypr/scripts/screensaver-awake.sh")
exec(mainMod .. " + grave", home .. "/.config/hypr/scripts/scratchpad-manager.sh toggle scene")
exec(mainMod .. " + backslash", home .. "/.config/hypr/scripts/sidepanel.sh toggle")
exec(mainMod .. " + SHIFT + backslash", home .. "/.config/hypr/scripts/sidepanel.sh send")
exec(mainMod .. " + CTRL + backslash", home .. "/.config/hypr/scripts/sidepanel.sh stash")
exec(mainMod .. " + S", home .. "/.config/hypr/scripts/scratchpad-manager.sh menu")
exec(mainMod .. " + CTRL + S", home .. "/.config/hypr/scripts/scratchpad-manager.sh launch logs")
exec(mainMod .. " + ALT + S", home .. "/.config/hypr/scripts/scratchpad-manager.sh launch ai")
exec(mainMod .. " + CTRL + ALT + S", home .. "/.config/hypr/scripts/scratchpad-manager.sh launch db")
exec(mainMod .. " + ALT + O", home .. "/.config/hypr/scripts/scratchpad-manager.sh launch obsidian")
exec(mainMod .. " + W", ctx.overview)
exec(mainMod .. " + tab", home .. "/.config/hypr/scripts/super-tab-overview.sh")
exec(mainMod .. " + SHIFT + tab", ctx.overview)
exec(mainMod .. " + O", home .. "/.config/hypr/scripts/set-wallpaper.sh --pick")
exec(mainMod .. " + SHIFT + O", home .. "/.config/hypr/scripts/set-wallpaper.sh --next")
exec(mainMod .. " + N", home .. "/.config/hypr/scripts/notif-center-toggle.sh")
exec(mainMod .. " + ALT + N", home .. "/.config/hypr/scripts/notif-dnd-toggle.sh")
exec(mainMod .. " + CTRL + N", home .. "/.config/hypr/scripts/notification-summary.sh copy")
exec(mainMod .. " + CTRL + ALT + N", home .. "/.config/hypr/scripts/notif-clear.sh")
exec(mainMod .. " + SHIFT + N", home .. "/.config/hypr/scripts/open-notes.sh")
exec(mainMod .. " + ALT + E", home .. "/.config/hypr/scripts/open-notes.sh")
bind(mainMod .. " + SHIFT + Q", hl.dsp.window.kill())
exec(mainMod .. " + SHIFT + M", home .. "/.config/hypr/scripts/minimize-window.sh minimize")
exec(mainMod .. " + F", home .. "/.config/hypr/scripts/float-toggle-smart.sh")
bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "maximized" }))
bind(mainMod .. " + CTRL + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
bind(mainMod .. " + M", hl.dsp.window.fullscreen({ mode = "maximized" }))
exec(mainMod .. " + V", home .. "/.config/hypr/scripts/float-toggle-smart.sh")
bind(mainMod .. " + SHIFT + P", hl.dsp.window.pseudo())
bind(mainMod .. " + C", hl.dsp.window.center())
