#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
ROOT_DIR="$(cd "$(dirname "$SCRIPT_PATH")/../../.." && pwd)"
SETTINGS_DIR="$ROOT_DIR/settings"
DEFAULTS="$SETTINGS_DIR/defaults.json"
STATE="$SETTINGS_DIR/state.json"
LOCAL_STATE="$SETTINGS_DIR/state.local.json"
PROFILES_DIR="$SETTINGS_DIR/profiles"
LOCK_CFG="$ROOT_DIR/hypr/hyprlock.conf"
MIME_CFG="$ROOT_DIR/mime/mimeapps.list"
GENERATED_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/hypr"
GENERATED_SETTINGS="$GENERATED_DIR/settings.generated.lua"
GENERATED_ANIMATIONS="$GENERATED_DIR/animation-settings.generated.lua"
GENERATED_LOCK="$GENERATED_DIR/lock-settings.generated.conf"
APP_ROUTING_FILE="$GENERATED_DIR/app-routing.generated.json"

mkdir -p "$GENERATED_DIR"

empty_json_file() {
  local f
  f="$(mktemp)"
  printf '{}\n' >"$f"
  printf '%s' "$f"
}

merged_json() {
  local tmp_empty profile base profile_file
  tmp_empty="$(empty_json_file)"

  base="$(jq -s '.[0] * .[1] * .[2]' "$DEFAULTS" "$STATE" "${LOCAL_STATE:-$tmp_empty}" 2>/dev/null || jq -s '.[0] * .[1] * .[2]' "$DEFAULTS" "$STATE" "$tmp_empty")"
  profile="$(jq -r '.machine.profile // "laptop"' <<<"$base")"
  profile_file="$PROFILES_DIR/$profile.json"

  if [[ -f "$profile_file" ]]; then
    jq -s '.[0] * .[1] * .[2] * .[3]' "$DEFAULTS" "$profile_file" "$STATE" "${LOCAL_STATE:-$tmp_empty}" 2>/dev/null ||
      jq -s '.[0] * .[1] * .[2] * .[3]' "$DEFAULTS" "$profile_file" "$STATE" "$tmp_empty"
  else
    jq -s '.[0] * .[1] * .[2]' "$DEFAULTS" "$STATE" "${LOCAL_STATE:-$tmp_empty}" 2>/dev/null ||
      jq -s '.[0] * .[1] * .[2]' "$DEFAULTS" "$STATE" "$tmp_empty"
  fi

  rm -f "$tmp_empty"
}

apply_notifications() {
  local json
  json="$1"
  jq '{notifications: .notifications}' <<<"$json" >"$GENERATED_DIR/notifications-settings.generated.json"
}

apply_action_center() {
  local json
  json="$1"
  jq '{action_center: .action_center}' <<<"$json" >"$GENERATED_DIR/action-center-settings.generated.json"
}

apply_sounds() {
  local json
  json="$1"
  jq '{sounds: .notifications.sounds}' <<<"$json" >"$GENERATED_DIR/notification-sounds.generated.json"
}

apply_lock_screen() {
  local json blur brightness vibrancy
  json="$1"
  blur="$(jq -r '.lock_screen.blur_passes' <<<"$json")"
  brightness="$(jq -r '.lock_screen.brightness' <<<"$json")"
  vibrancy="$(jq -r '.lock_screen.vibrancy' <<<"$json")"

  cat >"$GENERATED_LOCK" <<EOG
# Generated by settingsctl. Do not edit.
\$lock_blur = $blur
\$lock_brightness = $brightness
\$lock_vibrancy = $vibrancy
EOG

  if ! rg -q '^source = ~/.cache/hypr/lock-settings.generated.conf$' "$LOCK_CFG"; then
    printf '\nsource = ~/.cache/hypr/lock-settings.generated.conf\n' >>"$LOCK_CFG"
  fi
}

apply_hypr_overlay() {
  local json
  json="$1"

  cat >"$GENERATED_SETTINGS" <<EOG
-- Generated by settingsctl. Do not edit.
hl.config({
  input = {
    kb_layout = $(jq -r '.input.kb_layout | @json' <<<"$json"),
    touchpad = {
      natural_scroll = $(jq -r '.input.touchpad_natural_scroll' <<<"$json"),
    },
  },
})
EOG
}

apply_animations() {
  local json enabled blur blur_samples border_angle zoom spring window_speed workspace_speed workspace_distance special_distance
  json="$1"
  enabled="$(jq -r '.animations.enabled' <<<"$json")"
  blur="$(jq -r '.animations.motion_blur' <<<"$json")"
  blur_samples="$(jq -r '.animations.motion_blur_samples' <<<"$json")"
  border_angle="$(jq -r '.animations.border_angle' <<<"$json")"
  zoom="$(jq -r '.animations.zoom' <<<"$json")"
  spring="$(jq -r '.animations.spring' <<<"$json")"
  window_speed="$(jq -r '.animations.window_speed' <<<"$json")"
  workspace_speed="$(jq -r '.animations.workspace_speed' <<<"$json")"
  workspace_distance="$(jq -r '.animations.workspace_distance' <<<"$json")"
  special_distance="$(jq -r '.animations.special_workspace_distance' <<<"$json")"

  cat >"$GENERATED_ANIMATIONS" <<EOG
-- Generated by settingsctl. Do not edit.
hl.animation({ leaf = "global", enabled = $enabled, speed = 8, bezier = "ui" })
hl.animation({ leaf = "borderangle", enabled = $border_angle, speed = 10, bezier = "ui" })
hl.animation({ leaf = "zoomFactor", enabled = $zoom, speed = 6, bezier = "ui" })
hl.animation({ leaf = "windowsOut", enabled = $enabled, speed = 5, bezier = "windowOut", style = "popin 94%" })
hl.animation({ leaf = "layersOut", enabled = $enabled, speed = 6, bezier = "layerOut", style = "fade" })
hl.animation({ leaf = "fadeIn", enabled = $enabled, speed = 3, bezier = "ui" })
hl.animation({ leaf = "fadeOut", enabled = $enabled, speed = 5, bezier = "windowOut" })
hl.animation({ leaf = "workspacesOut", enabled = $enabled, speed = 5, bezier = "workspaceExit", style = "slidefade $workspace_distance%" })
hl.animation({ leaf = "specialWorkspaceOut", enabled = $enabled, speed = 5, bezier = "workspaceExit", style = "slidefadevert $special_distance%" })
hl.config({ decoration = { motion_blur = { enabled = $blur, samples = $blur_samples } } })
EOG

  if [[ "$spring" == "true" ]]; then
    cat >>"$GENERATED_ANIMATIONS" <<EOG
hl.animation({ leaf = "windows", enabled = $enabled, speed = $window_speed, spring = "windowIn", style = "popin 88%" })
hl.animation({ leaf = "windowsIn", enabled = $enabled, speed = $window_speed, spring = "windowIn", style = "popin 84%" })
hl.animation({ leaf = "fadeIn", enabled = $enabled, speed = 7, spring = "windowIn" })
hl.animation({ leaf = "fadeOut", enabled = $enabled, speed = 5, bezier = "windowOut" })
hl.animation({ leaf = "windowsMove", enabled = $enabled, speed = $window_speed, spring = "windowMove" })
hl.animation({ leaf = "layers", enabled = $enabled, speed = $window_speed, spring = "layerIn", style = "popin 82%" })
hl.animation({ leaf = "layersIn", enabled = $enabled, speed = $window_speed, spring = "layerIn", style = "popin 76%" })
hl.animation({ leaf = "workspaces", enabled = $enabled, speed = $workspace_speed, spring = "workspaceFlow", style = "slidefade $workspace_distance%" })
hl.animation({ leaf = "workspacesIn", enabled = $enabled, speed = $workspace_speed, spring = "workspaceFlow", style = "slidefade $workspace_distance%" })
hl.animation({ leaf = "specialWorkspace", enabled = $enabled, speed = $workspace_speed, spring = "windowIn", style = "slidefadevert $special_distance%" })
hl.animation({ leaf = "specialWorkspaceIn", enabled = $enabled, speed = $workspace_speed, spring = "windowIn", style = "slidefadevert $special_distance%" })
EOG
  else
    cat >>"$GENERATED_ANIMATIONS" <<'EOG'
hl.animation({ leaf = "windows", enabled = true, speed = 3, bezier = "ui", style = "popin 96%" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "ui", style = "popin 96%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "ui" })
hl.animation({ leaf = "layers", enabled = true, speed = 3, bezier = "ui", style = "fade" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 3, bezier = "ui", style = "fade" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 3, bezier = "ui", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 3, bezier = "ui", style = "fade" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3, bezier = "ui", style = "fade" })
hl.animation({ leaf = "specialWorkspaceIn", enabled = true, speed = 3, bezier = "ui", style = "fade" })
EOG
  fi
}

apply_wallpaper() {
  local json
  json="$1"
  jq '{wallpaper: .wallpaper}' <<<"$json" >"$GENERATED_DIR/wallpaper-settings.generated.json"
}

apply_panel() {
  local json
  json="$1"
  jq '{panel: .panel}' <<<"$json" >"$GENERATED_DIR/panel-settings.generated.json"
}

apply_power() {
  local json profile auto_profile watcher live_watcher
  json="$1"
  profile="$(jq -r '.power.default_profile' <<<"$json")"
  auto_profile="$(jq -r '.power.auto_profile' <<<"$json")"
  watcher="$ROOT_DIR/hypr/scripts/power-profile-auto.sh"
  live_watcher="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/scripts/power-profile-auto.sh"

  if [[ "$auto_profile" == "true" ]]; then
    if [[ -x "$watcher" ]] && ! pgrep -f "$watcher" >/dev/null 2>&1 && ! pgrep -f "$live_watcher" >/dev/null 2>&1; then
      "$watcher" >/dev/null 2>&1 &
    fi
  else
    pkill -f "$watcher" >/dev/null 2>&1 || true
    [[ "$live_watcher" == "$watcher" ]] || pkill -f "$live_watcher" >/dev/null 2>&1 || true
  fi

  # With automation disabled, the configured profile is authoritative.
  # With automation enabled, the watcher owns AC/battery transitions.
  if [[ "$auto_profile" != "true" ]] && command -v powerprofilesctl >/dev/null 2>&1; then
    powerprofilesctl set "$profile" >/dev/null 2>&1 || true
  fi
  jq '{power: .power}' <<<"$json" >"$GENERATED_DIR/power-settings.generated.json"
}

apply_input() {
  local json
  json="$1"
  jq '{input: .input}' <<<"$json" >"$GENERATED_DIR/input-settings.generated.json"
}

apply_startup() {
  local json autostart_file enabled
  json="$1"
  autostart_file="$HOME/.config/autostart/nvidia-settings-load.desktop"
  enabled="$(jq -r '.startup.nvidia_settings_autoload' <<<"$json")"

  if [[ "$enabled" == "true" ]] && command -v nvidia-settings >/dev/null 2>&1; then
    mkdir -p "$(dirname "$autostart_file")"
    cat >"$autostart_file" <<EOD
[Desktop Entry]
Type=Application
Name=Load NVIDIA Settings
Exec=nvidia-settings --load-config-only --config=$HOME/.config/nvidia-settings-rc
X-GNOME-Autostart-enabled=true
NoDisplay=true
EOD
  else
    rm -f "$autostart_file"
  fi
}

apply_app_routing() {
  local json
  json="$1"
  jq '.app_routing' <<<"$json" >"$APP_ROUTING_FILE"
}

apply_privacy() {
  local json
  json="$1"
  jq '{privacy: .privacy}' <<<"$json" >"$GENERATED_DIR/privacy-settings.generated.json"
}

apply_default_apps() {
  local json browser image user_mime
  json="$1"
  browser="$(jq -r '.default_apps.browser_desktop' <<<"$json")"
  image="$(jq -r '.default_apps.image_viewer_desktop' <<<"$json")"

  [[ -f "$MIME_CFG" ]] || return 0
  tmp="$(mktemp)"
  cp "$MIME_CFG" "$tmp"

  sed -i -E "s#^text/html=.*#text/html=${browser}#" "$tmp"
  sed -i -E "s#^x-scheme-handler/http=.*#x-scheme-handler/http=${browser}#" "$tmp"
  sed -i -E "s#^x-scheme-handler/https=.*#x-scheme-handler/https=${browser}#" "$tmp"
  sed -i -E "s#^image/png=.*#image/png=${image}#" "$tmp"
  sed -i -E "s#^image/jpeg=.*#image/jpeg=${image}#" "$tmp"

  mv "$tmp" "$MIME_CFG"

  user_mime="$HOME/.local/share/applications/mimeapps.list"
  mkdir -p "$(dirname "$user_mime")"
  cp "$MIME_CFG" "$user_mime"
}

section="${1:-all}"
json="$(merged_json)"

case "$section" in
  notifications) apply_notifications "$json" ;;
  action-center | action_center) apply_action_center "$json" ;;
  sounds) apply_sounds "$json" ;;
  lock-screen | lock_screen) apply_lock_screen "$json" ;;
  animations) apply_animations "$json" ;;
  wallpaper) apply_wallpaper "$json" ;;
  panel) apply_panel "$json" ;;
  power) apply_power "$json" ;;
  input) apply_input "$json" ;;
  startup) apply_startup "$json" ;;
  app-routing | app_routing) apply_app_routing "$json" ;;
  privacy) apply_privacy "$json" ;;
  default-apps | default_apps) apply_default_apps "$json" ;;
  all)
    apply_notifications "$json"
    apply_action_center "$json"
    apply_sounds "$json"
    apply_lock_screen "$json"
    apply_hypr_overlay "$json"
    apply_animations "$json"
    apply_wallpaper "$json"
    apply_panel "$json"
    apply_power "$json"
    apply_input "$json"
    apply_startup "$json"
    apply_app_routing "$json"
    apply_privacy "$json"
    apply_default_apps "$json"
    ;;
  *)
    echo "Unknown section: $section" >&2
    exit 1
    ;;
esac

if [[ "$section" == "animations" || "$section" == "all" ]] &&
  [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]] && command -v hyprctl >/dev/null 2>&1; then
  hyprctl reload >/dev/null 2>&1 || true
fi

echo "Applied settings section: $section"
