#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
ROOT_DIR="$(cd "$(dirname "$SCRIPT_PATH")/../../.." && pwd)"
SETTINGS_DIR="$ROOT_DIR/settings"
DEFAULTS="$SETTINGS_DIR/defaults.json"
STATE="$SETTINGS_DIR/state.json"
LOCAL_STATE="$SETTINGS_DIR/state.local.json"
PROFILES_DIR="$SETTINGS_DIR/profiles"
LOCK_CFG="$ROOT_DIR/hypr/hyprlock.conf"
HYPR_CONF="$ROOT_DIR/hypr/hyprland.conf"
MIME_CFG="$ROOT_DIR/mime/mimeapps.list"
GENERATED_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/hypr"
GENERATED_SETTINGS="$GENERATED_DIR/settings.generated.conf"
GENERATED_LOCK="$GENERATED_DIR/lock-settings.generated.conf"
APP_ROUTING_FILE="$GENERATED_DIR/app-routing.generated.json"

mkdir -p "$GENERATED_DIR"

empty_json_file() {
  local f
  f="$(mktemp)"
  printf '{}\n' > "$f"
  printf '%s' "$f"
}

merged_json() {
  local tmp_empty profile base profile_file
  tmp_empty="$(empty_json_file)"

  base="$(jq -s '.[0] * .[1] * .[2]' "$DEFAULTS" "$STATE" "${LOCAL_STATE:-$tmp_empty}" 2>/dev/null || jq -s '.[0] * .[1] * .[2]' "$DEFAULTS" "$STATE" "$tmp_empty")"
  profile="$(jq -r '.machine.profile // "laptop"' <<<"$base")"
  profile_file="$PROFILES_DIR/$profile.json"

  if [[ -f "$profile_file" ]]; then
    jq -s '.[0] * .[1] * .[2] * .[3]' "$DEFAULTS" "$profile_file" "$STATE" "${LOCAL_STATE:-$tmp_empty}" 2>/dev/null \
      || jq -s '.[0] * .[1] * .[2] * .[3]' "$DEFAULTS" "$profile_file" "$STATE" "$tmp_empty"
  else
    jq -s '.[0] * .[1] * .[2]' "$DEFAULTS" "$STATE" "${LOCAL_STATE:-$tmp_empty}" 2>/dev/null \
      || jq -s '.[0] * .[1] * .[2]' "$DEFAULTS" "$STATE" "$tmp_empty"
  fi

  rm -f "$tmp_empty"
}

apply_notifications() {
  local json
  json="$1"
  jq '{notifications: .notifications}' <<<"$json" > "$GENERATED_DIR/notifications-settings.generated.json"
}

apply_action_center() {
  local json
  json="$1"
  jq '{action_center: .action_center}' <<<"$json" > "$GENERATED_DIR/action-center-settings.generated.json"
}

apply_sounds() {
  local json
  json="$1"
  jq '{sounds: .notifications.sounds}' <<<"$json" > "$GENERATED_DIR/notification-sounds.generated.json"
}

apply_lock_screen() {
  local json blur brightness vibrancy
  json="$1"
  blur="$(jq -r '.lock_screen.blur_passes' <<<"$json")"
  brightness="$(jq -r '.lock_screen.brightness' <<<"$json")"
  vibrancy="$(jq -r '.lock_screen.vibrancy' <<<"$json")"

  cat > "$GENERATED_LOCK" <<EOG
# Generated by settingsctl. Do not edit.
\$lock_blur = $blur
\$lock_brightness = $brightness
\$lock_vibrancy = $vibrancy
EOG

  if ! rg -q '^source = ~/.cache/hypr/lock-settings.generated.conf$' "$LOCK_CFG"; then
    printf '\nsource = ~/.cache/hypr/lock-settings.generated.conf\n' >> "$LOCK_CFG"
  fi
}

apply_hypr_overlay() {
  local json
  json="$1"

  cat > "$GENERATED_SETTINGS" <<EOG
# Generated by settingsctl. Do not edit.
input {
    kb_layout = $(jq -r '.input.kb_layout' <<<"$json")
    touchpad {
        natural_scroll = $(jq -r '.input.touchpad_natural_scroll' <<<"$json")
    }
}

gestures {
    workspace_swipe_forever = $(jq -r '.input.workspace_swipe' <<<"$json")
}

env = HYPR_ENABLE_NM_APPLET,$(jq -r 'if .startup.nm_applet_autostart then 1 else 0 end' <<<"$json")
env = HYPR_ENABLE_BLUEMAN_APPLET,$(jq -r 'if .startup.blueman_applet_autostart then 1 else 0 end' <<<"$json")
EOG

  if ! rg -q '^source = ~/.cache/hypr/settings.generated.conf$' "$HYPR_CONF"; then
    printf '\nsource = ~/.cache/hypr/settings.generated.conf\n' >> "$HYPR_CONF"
  fi
}

apply_wallpaper() {
  local json
  json="$1"
  jq '{wallpaper: .wallpaper}' <<<"$json" > "$GENERATED_DIR/wallpaper-settings.generated.json"
}

apply_panel() {
  local json
  json="$1"
  jq '{panel: .panel}' <<<"$json" > "$GENERATED_DIR/panel-settings.generated.json"
}

apply_power() {
  local json profile
  json="$1"
  profile="$(jq -r '.power.default_profile' <<<"$json")"
  if command -v powerprofilesctl >/dev/null 2>&1; then
    powerprofilesctl set "$profile" >/dev/null 2>&1 || true
  fi
  jq '{power: .power}' <<<"$json" > "$GENERATED_DIR/power-settings.generated.json"
}

apply_input() {
  local json
  json="$1"
  jq '{input: .input}' <<<"$json" > "$GENERATED_DIR/input-settings.generated.json"
}

apply_startup() {
  local json autostart_file enabled
  json="$1"
  autostart_file="$HOME/.config/autostart/nvidia-settings-load.desktop"
  enabled="$(jq -r '.startup.nvidia_settings_autoload' <<<"$json")"

  if [[ "$enabled" == "true" ]] && command -v nvidia-settings >/dev/null 2>&1; then
    mkdir -p "$(dirname "$autostart_file")"
    cat > "$autostart_file" <<EOD
[Desktop Entry]
Type=Application
Name=Load NVIDIA Settings
Exec=nvidia-settings --load-config-only --config=$HOME/.config/nvidia-settings-rc
X-GNOME-Autostart-enabled=true
NoDisplay=true
EOD
  else
    rm -f "$autostart_file"
  fi
}

apply_app_routing() {
  local json
  json="$1"
  jq '.app_routing' <<<"$json" > "$APP_ROUTING_FILE"
}

apply_privacy() {
  local json
  json="$1"
  jq '{privacy: .privacy}' <<<"$json" > "$GENERATED_DIR/privacy-settings.generated.json"
}

apply_default_apps() {
  local json browser image user_mime
  json="$1"
  browser="$(jq -r '.default_apps.browser_desktop' <<<"$json")"
  image="$(jq -r '.default_apps.image_viewer_desktop' <<<"$json")"

  [[ -f "$MIME_CFG" ]] || return 0
  tmp="$(mktemp)"
  cp "$MIME_CFG" "$tmp"

  sed -i -E "s#^text/html=.*#text/html=${browser}#" "$tmp"
  sed -i -E "s#^x-scheme-handler/http=.*#x-scheme-handler/http=${browser}#" "$tmp"
  sed -i -E "s#^x-scheme-handler/https=.*#x-scheme-handler/https=${browser}#" "$tmp"
  sed -i -E "s#^image/png=.*#image/png=${image}#" "$tmp"
  sed -i -E "s#^image/jpeg=.*#image/jpeg=${image}#" "$tmp"

  mv "$tmp" "$MIME_CFG"

  user_mime="$HOME/.local/share/applications/mimeapps.list"
  mkdir -p "$(dirname "$user_mime")"
  cp "$MIME_CFG" "$user_mime"
}

section="${1:-all}"
json="$(merged_json)"

case "$section" in
  notifications) apply_notifications "$json" ;;
  action-center|action_center) apply_action_center "$json" ;;
  sounds) apply_sounds "$json" ;;
  lock-screen|lock_screen) apply_lock_screen "$json" ;;
  wallpaper) apply_wallpaper "$json" ;;
  panel) apply_panel "$json" ;;
  power) apply_power "$json" ;;
  input) apply_input "$json" ;;
  startup) apply_startup "$json" ;;
  app-routing|app_routing) apply_app_routing "$json" ;;
  privacy) apply_privacy "$json" ;;
  default-apps|default_apps) apply_default_apps "$json" ;;
  all)
    apply_notifications "$json"
    apply_action_center "$json"
    apply_sounds "$json"
    apply_lock_screen "$json"
    apply_hypr_overlay "$json"
    apply_wallpaper "$json"
    apply_panel "$json"
    apply_power "$json"
    apply_input "$json"
    apply_startup "$json"
    apply_app_routing "$json"
    apply_privacy "$json"
    apply_default_apps "$json"
    ;;
  *)
    echo "Unknown section: $section" >&2
    exit 1
    ;;
esac

echo "Applied settings section: $section"
